In [5]:
# GAUSS ELIMINATION METHOD

print("GIVEN QUESTION: Solve the system of equations using Gauss Elimination Method.")
print("The system of equations is:\n")
print("3x + 2y + z = 1")
print("2x + 3y + 2z = 2")
print("x + 2y + 3z = 3")

# Step 1: Define the augmented matrix
A = np.array([[3, 2, 1, 1],  # Augmented matrix [A|b]
              [2, 3, 2, 2],
              [1, 2, 3, 3]], dtype=float)

# Step 2: Gauss Elimination method function
def gauss_elimination(A):
    n = len(A)
    
    # Forward Elimination
    for i in range(n):
        # Make the diagonal element A[i][i] to 1
        if A[i][i] == 0:
            print("Pivot is zero. Gauss Elimination method fails.")
            return None

        # Make the diagonal element to be 1 (by scaling the row)
        A[i] = A[i] / A[i][i]

        # Eliminate elements below the pivot
        for j in range(i + 1, n):
            factor = A[j][i]
            A[j] = A[j] - factor * A[i]
        
        print(f"\nAfter step {i + 1} (Forward Elimination):")
        print(A)

    # Back Substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = A[i][n] - np.dot(A[i, i + 1:n], x[i + 1:])
        print(f"\nBack Substitution step {n - i}:")
        print(f"x[{i}] = {x[i]}")

    print("\nSolution:")
    for i in range(n):
        print(f"x{i+1} = {x[i]}")

# Step 3: Call Gauss Elimination with the augmented matrix
gauss_elimination(A)


GIVEN QUESTION: Solve the system of equations using Gauss Elimination Method.
The system of equations is:

3x + 2y + z = 1
2x + 3y + 2z = 2
x + 2y + 3z = 3

After step 1 (Forward Elimination):
[[1.         0.66666667 0.33333333 0.33333333]
 [0.         1.66666667 1.33333333 1.33333333]
 [0.         1.33333333 2.66666667 2.66666667]]

After step 2 (Forward Elimination):
[[1.         0.66666667 0.33333333 0.33333333]
 [0.         1.         0.8        0.8       ]
 [0.         0.         1.6        1.6       ]]

After step 3 (Forward Elimination):
[[1.         0.66666667 0.33333333 0.33333333]
 [0.         1.         0.8        0.8       ]
 [0.         0.         1.         1.        ]]

Back Substitution step 1:
x[2] = 1.0

Back Substitution step 2:
x[1] = 0.0

Back Substitution step 3:
x[0] = 0.0

Solution:
x1 = 0.0
x2 = 0.0
x3 = 1.0
