In [4]:
# LU DECOMPOSITION METHOD

import numpy as np
import pandas as pd

print("GIVEN QUESTION: Solve the system of equations using LU Decomposition.")
print("The system of equations is:\n")
print("10x + y + 2z = 27")
print("x + 10y + z = -11")
print("2x + y + 10z = 17")

# Step 1: Define the augmented matrix (Ax = b)
A = np.array([[10, 1, 2],  # Coefficients of the system
              [1, 10, 1],
              [2, 1, 10]], dtype=float)

b = np.array([27, -11, 17], dtype=float)  # Constants of the system

# Step 2: LU Decomposition function
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n), dtype=float)  # Lower triangular matrix
    U = np.zeros((n, n), dtype=float)  # Upper triangular matrix
    
    # Decompose A into L and U
    for i in range(n):
        # Upper Triangular Matrix U
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        
        # Lower Triangular Matrix L
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
        
        L[i, i] = 1  # Diagonal of L is 1
    
    return L, U

# Step 3: Forward substitution to solve Ly = b
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n, dtype=float)
    
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    
    return y

# Step 4: Backward substitution to solve Ux = y
def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n, dtype=float)
    
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x

# Step 5: LU Decomposition and solving system
def solve_system(A, b):
    L, U = lu_decomposition(A)
    print(f"\nLower Triangular Matrix L:\n{L}")
    print(f"\nUpper Triangular Matrix U:\n{U}")
    
    # Step 6: Solve Ly = b
    y = forward_substitution(L, b)
    print(f"\nSolution of Ly = b (y):\n{y}")
    
    # Step 7: Solve Ux = y
    x = backward_substitution(U, y)
    print(f"\nSolution of Ux = y (x):\n{x}")
    
    return x

# Step 8: Call the function to solve the system
solution = solve_system(A, b)


GIVEN QUESTION: Solve the system of equations using LU Decomposition.
The system of equations is:

10x + y + 2z = 27
x + 10y + z = -11
2x + y + 10z = 17

Lower Triangular Matrix L:
[[1.         0.         0.        ]
 [0.1        1.         0.        ]
 [0.2        0.08080808 1.        ]]

Upper Triangular Matrix U:
[[10.          1.          2.        ]
 [ 0.          9.9         0.8       ]
 [ 0.          0.          9.53535354]]

Solution of Ly = b (y):
[ 27.         -13.7         12.70707071]

Solution of Ux = y (x):
[ 2.58262712 -1.49152542  1.33262712]
